# Generated by Django 4.2.3 on 2023-09-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='desc',
            new_name='disc',
        ),
    ]
