# Generated by Django 4.2.3 on 2023-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0002_rename_desc_items_disc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True)),
                ('gender', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
            ],
        ),
    ]
